server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/promtail_positions.yaml

clients:
  - url: http://localhost:3100/loki/api/v1/push

scrape_configs:
  - job_name: system
    static_configs:
      - targets: [ localhost ]
        labels:
          job: varlogs
          __path__: /var/log/*log

  # Si vous souhaitez récupérer les logs Docker (selon configuration), ajoutez un scrape pour les fichiers de logs
  - job_name: docker
    static_configs:
      - targets: [ localhost ]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*-json.log
