name: CI

on:
  push:
    branches: [ main ]

defaults:
  run:
    shell: bash

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout (shallow)
        uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Cache pip
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt', '**/extra/mlflow/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install Python dependencies (if any)
        run: |
          if [ -f requirements.txt ]; then
            python -m pip install --upgrade pip
            pip install -r requirements.txt
          else
            echo "No requirements.txt — skipping pip install"
          fi

      - name: Install MLflow dependencies
        run: |
          if [ -f extra/mlflow/requirements.txt ]; then
            pip install -r extra/mlflow/requirements.txt
          fi

      - name: Run MLflow example
        run: |
          python extra/mlflow/mlflow_example.py

      - name: Smoke-test app (start, request, stop)
        run: |
          bash scripts/ci_smoke.sh

      - name: Run sysinfo script (bash)
        run: |
          bash scripts/sysinfo.sh
